# Generated by Django 3.2.7 on 2022-02-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('channelNom', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('speudo', models.CharField(max_length=20)),
            ],
        ),
    ]
