# Generated by Django 3.2.7 on 2022-02-27 22:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 27, 22, 36, 31, 534949, tzinfo=utc)),
        ),
    ]
